#规划GateWay的服务端口
server:
  port: 18888
##规划gateWay注册到到nacos上的服务应用名称
spring:
  application:
    name: nirvana-gateway
  main:
    allow-circular-references: true # 允许循环依赖，因为项目是三层架构，无法避免这个情况。
    allow-bean-definition-overriding: true # 允许 Bean 覆盖，例如说 Dubbo 或者 Feign 等会存在重复定义的服务

#开启acutor端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      #打开端点详情
      show-details: always


# logging
logging:
  config: classpath:logback-spring.xml


