package com.phoenix.nirvana.service.system.convert;

import com.phoenix.nirvana.service.system.dal.mysql.dataobject.SysErrorCodeDO;
import com.phoenix.nirvana.service.system.rpc.admin.domain.dto.ErrorCodeAutoGenerateDTO;
import com.phoenix.nirvana.service.system.rpc.admin.domain.vo.errorcode.SysErrorCodeVO;
import org.mapstruct.Mapper;
import org.mapstruct.Mappings;
import org.mapstruct.factory.Mappers;

import java.util.List;

@Mapper
public interface SysErrorCodeConvert {

    SysErrorCodeConvert INTERFACE = Mappers.getMapper(SysErrorCodeConvert.class);

    @Mappings({})
    SysErrorCodeVO convert(SysErrorCodeDO sysErrorCodeDO);

    List<SysErrorCodeVO> convert(List<SysErrorCodeDO> sysErrorCodeDO);

    SysErrorCodeDO convert(ErrorCodeAutoGenerateDTO errorCodeAutoGenerateDTO);

}
