spring:
  application:
    name: mall-order-biz
  main:
    allow-circular-references: true # 允许循环依赖，因为项目是三层架构，无法避免这个情况。
    allow-bean-definition-overriding: true # 允许 Bean 覆盖，例如说 Dubbo 或者 Feign 等会存在重复定义的服务
  # Jackson 配置项
  jackson:
    serialization:
      write-dates-as-timestamps: true # 设置 Date 的格式，使用时间戳
      write-date-timestamps-as-nanoseconds: false # 设置不使用 nanoseconds 的格式。例如说 1611460870.401，而是直接 1611460870401
      write-durations-as-timestamps: true # 设置 Duration 的格式，使用时间戳
      fail-on-empty-beans: false # 允许序列化无属性的 Bean
  profiles:
    active: local
  resources:
    add-mappings: false
server:
  port: 19010
  tomcat:
    max-connections: 200
    max-threads: 800
    accept-count: 1000
    min-spare-threads: 100
  servlet:
    context-path: /

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.phoenix.nirvana.order.dal.mysql.dataobject

# logging
logging:
  config: classpath:logback-spring.xml
  file:
    path: ${user.home}/logs
